name       : python-ipaddress
version    : 1.0.22
release    : 3
source     :
    - https://github.com/phihag/ipaddress/archive/v1.0.22.tar.gz : 19b9a4e7ab0271a7f16b498cebe431d7d6179c7cd99626d918b5fa218f0ef8be
license    : Python-2.0
component  : programming.python
summary    : IPv4/IPv6 manipulation library
description: |
    IPv4/IPv6 manipulation library ipaddress for older Python versions.
build      : |
    %python_setup
install    : |
    %python_install
check      : |
    pushd $PKG_BUILD_DIR/py2build
        python test_ipaddress.py
    popd
