name       : python-ipaddress
version    : 1.0.19
release    : 2
source     :
    - https://github.com/phihag/ipaddress/archive/v1.0.19.tar.gz : 9bb06a4d5c3b18a6f8778170f248c21e8c081e5c373a0e937080d1a1de32fdd3
license    : Python-2.0
component  : programming.python
summary    : IPv4/IPv6 manipulation library
description: |
    IPv4/IPv6 manipulation library ipaddress for older Python versions.
build      : |
    %python_setup
install    : |
    %python_install
check      : |
    pushd $PKG_BUILD_DIR/py2build
        python test_ipaddress.py
    popd
