name       : python-ipaddress
version    : 1.0.23
release    : 4
source     :
    - https://github.com/phihag/ipaddress/archive/v1.0.23.tar.gz : 8cc01a7523042c3b1a01446f0318e8bbe0fc0d520ca651c986377e402a2e9b47
license    : Python-2.0
component  : programming.python
summary    : IPv4/IPv6 manipulation library
description: |
    IPv4/IPv6 manipulation library ipaddress for older Python versions.
build      : |
    %python_setup
install    : |
    %python_install
check      : |
    pushd $PKG_BUILD_DIR/py2build
        python test_ipaddress.py
    popd
